// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package info

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServicer creates a new instance of MockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicer {
	mock := &MockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

type MockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicer) EXPECT() *MockServicer_Expecter {
	return &MockServicer_Expecter{mock: &_m.Mock}
}

// getAppInfo provides a mock function for the type MockServicer
func (_mock *MockServicer) getAppInfo() (*response, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAppInfo")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*response, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *response); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getAppInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAppInfo'
type MockServicer_getAppInfo_Call struct {
	*mock.Call
}

// getAppInfo is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAppInfo() *MockServicer_getAppInfo_Call {
	return &MockServicer_getAppInfo_Call{Call: _e.mock.On("getAppInfo")}
}

func (_c *MockServicer_getAppInfo_Call) Run(run func()) *MockServicer_getAppInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAppInfo_Call) Return(responseMoqParam *response, err error) *MockServicer_getAppInfo_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_getAppInfo_Call) RunAndReturn(run func() (*response, error)) *MockServicer_getAppInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPServicer creates a new instance of MockIPServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPServicer {
	mock := &MockIPServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPServicer is an autogenerated mock type for the IPServicer type
type MockIPServicer struct {
	mock.Mock
}

type MockIPServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPServicer) EXPECT() *MockIPServicer_Expecter {
	return &MockIPServicer_Expecter{mock: &_m.Mock}
}

// lookupIP provides a mock function for the type MockIPServicer
func (_mock *MockIPServicer) lookupIP(s string) ([]net.IP, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for lookupIP")
	}

	var r0 []net.IP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]net.IP, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []net.IP); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPServicer_lookupIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'lookupIP'
type MockIPServicer_lookupIP_Call struct {
	*mock.Call
}

// lookupIP is a helper method to define mock.On call
//   - s string
func (_e *MockIPServicer_Expecter) lookupIP(s interface{}) *MockIPServicer_lookupIP_Call {
	return &MockIPServicer_lookupIP_Call{Call: _e.mock.On("lookupIP", s)}
}

func (_c *MockIPServicer_lookupIP_Call) Run(run func(s string)) *MockIPServicer_lookupIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPServicer_lookupIP_Call) Return(iPs []net.IP, err error) *MockIPServicer_lookupIP_Call {
	_c.Call.Return(iPs, err)
	return _c
}

func (_c *MockIPServicer_lookupIP_Call) RunAndReturn(run func(s string) ([]net.IP, error)) *MockIPServicer_lookupIP_Call {
	_c.Call.Return(run)
	return _c
}
