// Code generated by mockery v2.42.2. DO NOT EDIT.

package pet

import (
	repository "github.com/rhtran/gin-petclinic-service/pkg/infra/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockServicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

type MockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicer) EXPECT() *MockServicer_Expecter {
	return &MockServicer_Expecter{mock: &_m.Mock}
}

// create provides a mock function with given fields: pet
func (_m *MockServicer) create(pet *repository.Pet) (*Response, error) {
	ret := _m.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Pet) (*Response, error)); ok {
		return rf(pet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Pet) *Response); ok {
		r0 = rf(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Pet) error); ok {
		r1 = rf(pet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type MockServicer_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - pet *repository.Pet
func (_e *MockServicer_Expecter) create(pet interface{}) *MockServicer_create_Call {
	return &MockServicer_create_Call{Call: _e.mock.On("create", pet)}
}

func (_c *MockServicer_create_Call) Run(run func(pet *repository.Pet)) *MockServicer_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*repository.Pet))
	})
	return _c
}

func (_c *MockServicer_create_Call) Return(_a0 *Response, _a1 error) *MockServicer_create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_create_Call) RunAndReturn(run func(*repository.Pet) (*Response, error)) *MockServicer_create_Call {
	_c.Call.Return(run)
	return _c
}

// getAllPets provides a mock function with given fields:
func (_m *MockServicer) getAllPets() (*Responses, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllPets")
	}

	var r0 *Responses
	var r1 error
	if rf, ok := ret.Get(0).(func() (*Responses, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *Responses); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Responses)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getAllPets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllPets'
type MockServicer_getAllPets_Call struct {
	*mock.Call
}

// getAllPets is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllPets() *MockServicer_getAllPets_Call {
	return &MockServicer_getAllPets_Call{Call: _e.mock.On("getAllPets")}
}

func (_c *MockServicer_getAllPets_Call) Run(run func()) *MockServicer_getAllPets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllPets_Call) Return(_a0 *Responses, _a1 error) *MockServicer_getAllPets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getAllPets_Call) RunAndReturn(run func() (*Responses, error)) *MockServicer_getAllPets_Call {
	_c.Call.Return(run)
	return _c
}

// getPetById provides a mock function with given fields: id
func (_m *MockServicer) getPetById(id int) (*Response, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getPetById")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*Response, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getPetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPetById'
type MockServicer_getPetById_Call struct {
	*mock.Call
}

// getPetById is a helper method to define mock.On call
//   - id int
func (_e *MockServicer_Expecter) getPetById(id interface{}) *MockServicer_getPetById_Call {
	return &MockServicer_getPetById_Call{Call: _e.mock.On("getPetById", id)}
}

func (_c *MockServicer_getPetById_Call) Run(run func(id int)) *MockServicer_getPetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockServicer_getPetById_Call) Return(_a0 *Response, _a1 error) *MockServicer_getPetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getPetById_Call) RunAndReturn(run func(int) (*Response, error)) *MockServicer_getPetById_Call {
	_c.Call.Return(run)
	return _c
}

// getPetByIdWithVisits provides a mock function with given fields: id
func (_m *MockServicer) getPetByIdWithVisits(id int) (*Response, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getPetByIdWithVisits")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*Response, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getPetByIdWithVisits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPetByIdWithVisits'
type MockServicer_getPetByIdWithVisits_Call struct {
	*mock.Call
}

// getPetByIdWithVisits is a helper method to define mock.On call
//   - id int
func (_e *MockServicer_Expecter) getPetByIdWithVisits(id interface{}) *MockServicer_getPetByIdWithVisits_Call {
	return &MockServicer_getPetByIdWithVisits_Call{Call: _e.mock.On("getPetByIdWithVisits", id)}
}

func (_c *MockServicer_getPetByIdWithVisits_Call) Run(run func(id int)) *MockServicer_getPetByIdWithVisits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockServicer_getPetByIdWithVisits_Call) Return(_a0 *Response, _a1 error) *MockServicer_getPetByIdWithVisits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getPetByIdWithVisits_Call) RunAndReturn(run func(int) (*Response, error)) *MockServicer_getPetByIdWithVisits_Call {
	_c.Call.Return(run)
	return _c
}

// getPetByName provides a mock function with given fields: name
func (_m *MockServicer) getPetByName(name string) ([]Response, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for getPetByName")
	}

	var r0 []Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]Response, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []Response); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getPetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPetByName'
type MockServicer_getPetByName_Call struct {
	*mock.Call
}

// getPetByName is a helper method to define mock.On call
//   - name string
func (_e *MockServicer_Expecter) getPetByName(name interface{}) *MockServicer_getPetByName_Call {
	return &MockServicer_getPetByName_Call{Call: _e.mock.On("getPetByName", name)}
}

func (_c *MockServicer_getPetByName_Call) Run(run func(name string)) *MockServicer_getPetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServicer_getPetByName_Call) Return(_a0 []Response, _a1 error) *MockServicer_getPetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getPetByName_Call) RunAndReturn(run func(string) ([]Response, error)) *MockServicer_getPetByName_Call {
	_c.Call.Return(run)
	return _c
}

// update provides a mock function with given fields: pet
func (_m *MockServicer) update(pet *repository.Pet) (*Response, error) {
	ret := _m.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Pet) (*Response, error)); ok {
		return rf(pet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Pet) *Response); ok {
		r0 = rf(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Pet) error); ok {
		r1 = rf(pet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'update'
type MockServicer_update_Call struct {
	*mock.Call
}

// update is a helper method to define mock.On call
//   - pet *repository.Pet
func (_e *MockServicer_Expecter) update(pet interface{}) *MockServicer_update_Call {
	return &MockServicer_update_Call{Call: _e.mock.On("update", pet)}
}

func (_c *MockServicer_update_Call) Run(run func(pet *repository.Pet)) *MockServicer_update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*repository.Pet))
	})
	return _c
}

func (_c *MockServicer_update_Call) Return(_a0 *Response, _a1 error) *MockServicer_update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_update_Call) RunAndReturn(run func(*repository.Pet) (*Response, error)) *MockServicer_update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServicer creates a new instance of MockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicer {
	mock := &MockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
