/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVisitsIndexRouteImport } from './routes/_authenticated/visits/index'
import { Route as AuthenticatedVeterinariansIndexRouteImport } from './routes/_authenticated/veterinarians/index'
import { Route as AuthenticatedOwnersIndexRouteImport } from './routes/_authenticated/owners/index'
import { Route as AuthenticatedAddOwnerIndexRouteImport } from './routes/_authenticated/add-owner/index'
import { Route as AuthenticatedAboutIndexRouteImport } from './routes/_authenticated/about/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsIndexRoute =
  AuthenticatedVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVeterinariansIndexRoute =
  AuthenticatedVeterinariansIndexRouteImport.update({
    id: '/veterinarians/',
    path: '/veterinarians/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnersIndexRoute =
  AuthenticatedOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAddOwnerIndexRoute =
  AuthenticatedAddOwnerIndexRouteImport.update({
    id: '/add-owner/',
    path: '/add-owner/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAboutIndexRoute = AuthenticatedAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AuthenticatedAboutIndexRoute
  '/add-owner': typeof AuthenticatedAddOwnerIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/veterinarians': typeof AuthenticatedVeterinariansIndexRoute
  '/visits': typeof AuthenticatedVisitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AuthenticatedAboutIndexRoute
  '/add-owner': typeof AuthenticatedAddOwnerIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/veterinarians': typeof AuthenticatedVeterinariansIndexRoute
  '/visits': typeof AuthenticatedVisitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/about/': typeof AuthenticatedAboutIndexRoute
  '/_authenticated/add-owner/': typeof AuthenticatedAddOwnerIndexRoute
  '/_authenticated/owners/': typeof AuthenticatedOwnersIndexRoute
  '/_authenticated/veterinarians/': typeof AuthenticatedVeterinariansIndexRoute
  '/_authenticated/visits/': typeof AuthenticatedVisitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-owner'
    | '/owners'
    | '/veterinarians'
    | '/visits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/add-owner' | '/owners' | '/veterinarians' | '/visits'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/about/'
    | '/_authenticated/add-owner/'
    | '/_authenticated/owners/'
    | '/_authenticated/veterinarians/'
    | '/_authenticated/visits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/': {
      id: '/_authenticated/visits/'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veterinarians/': {
      id: '/_authenticated/veterinarians/'
      path: '/veterinarians'
      fullPath: '/veterinarians'
      preLoaderRoute: typeof AuthenticatedVeterinariansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/': {
      id: '/_authenticated/owners/'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AuthenticatedOwnersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-owner/': {
      id: '/_authenticated/add-owner/'
      path: '/add-owner'
      fullPath: '/add-owner'
      preLoaderRoute: typeof AuthenticatedAddOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about/': {
      id: '/_authenticated/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAboutIndexRoute: typeof AuthenticatedAboutIndexRoute
  AuthenticatedAddOwnerIndexRoute: typeof AuthenticatedAddOwnerIndexRoute
  AuthenticatedOwnersIndexRoute: typeof AuthenticatedOwnersIndexRoute
  AuthenticatedVeterinariansIndexRoute: typeof AuthenticatedVeterinariansIndexRoute
  AuthenticatedVisitsIndexRoute: typeof AuthenticatedVisitsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAboutIndexRoute: AuthenticatedAboutIndexRoute,
  AuthenticatedAddOwnerIndexRoute: AuthenticatedAddOwnerIndexRoute,
  AuthenticatedOwnersIndexRoute: AuthenticatedOwnersIndexRoute,
  AuthenticatedVeterinariansIndexRoute: AuthenticatedVeterinariansIndexRoute,
  AuthenticatedVisitsIndexRoute: AuthenticatedVisitsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
