// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// IPServicer is an autogenerated mock type for the IPServicer type
type IPServicer struct {
	mock.Mock
}

// LookupIP provides a mock function with given fields: host
func (_m *IPServicer) LookupIP(host string) ([]net.IP, error) {
	ret := _m.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for LookupIP")
	}

	var r0 []net.IP
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]net.IP, error)); ok {
		return rf(host)
	}
	if rf, ok := ret.Get(0).(func(string) []net.IP); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IP)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPServicer creates a new instance of IPServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPServicer {
	mock := &IPServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
