// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	repository "fiber-petclinic-service/pkg/repository"

	mock "github.com/stretchr/testify/mock"
)

// OwnerRepositorier is an autogenerated mock type for the OwnerRepositorier type
type OwnerRepositorier struct {
	mock.Mock
}

// FindAll provides a mock function with no fields
func (_m *OwnerRepositorier) FindAll() ([]repository.Owner, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []repository.Owner
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.Owner, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.Owner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Owner)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *OwnerRepositorier) FindById(id uint) (*repository.Owner, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *repository.Owner
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*repository.Owner, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *repository.Owner); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Owner)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdWithPets provides a mock function with given fields: id
func (_m *OwnerRepositorier) FindByIdWithPets(id uint) (*repository.Owner, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdWithPets")
	}

	var r0 *repository.Owner
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*repository.Owner, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *repository.Owner); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Owner)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByLastName provides a mock function with given fields: lastName
func (_m *OwnerRepositorier) FindByLastName(lastName string) ([]repository.Owner, error) {
	ret := _m.Called(lastName)

	if len(ret) == 0 {
		panic("no return value specified for FindByLastName")
	}

	var r0 []repository.Owner
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]repository.Owner, error)); ok {
		return rf(lastName)
	}
	if rf, ok := ret.Get(0).(func(string) []repository.Owner); ok {
		r0 = rf(lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Owner)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: owner
func (_m *OwnerRepositorier) Insert(owner *repository.Owner) (*repository.Owner, error) {
	ret := _m.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *repository.Owner
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Owner) (*repository.Owner, error)); ok {
		return rf(owner)
	}
	if rf, ok := ret.Get(0).(func(*repository.Owner) *repository.Owner); ok {
		r0 = rf(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Owner)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Owner) error); ok {
		r1 = rf(owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: owner
func (_m *OwnerRepositorier) Update(owner *repository.Owner) (*repository.Owner, error) {
	ret := _m.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Owner
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Owner) (*repository.Owner, error)); ok {
		return rf(owner)
	}
	if rf, ok := ret.Get(0).(func(*repository.Owner) *repository.Owner); ok {
		r0 = rf(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Owner)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Owner) error); ok {
		r1 = rf(owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOwnerRepositorier creates a new instance of OwnerRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOwnerRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *OwnerRepositorier {
	mock := &OwnerRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
