// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	repository "fiber-petclinic-service/pkg/repository"

	mock "github.com/stretchr/testify/mock"
)

// PetRepositorier is an autogenerated mock type for the PetRepositorier type
type PetRepositorier struct {
	mock.Mock
}

// FindAll provides a mock function with no fields
func (_m *PetRepositorier) FindAll() ([]repository.Pet, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []repository.Pet
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.Pet, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.Pet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Pet)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *PetRepositorier) FindById(id int) (*repository.Pet, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *repository.Pet
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*repository.Pet, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *repository.Pet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Pet)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdWithVisits provides a mock function with given fields: id
func (_m *PetRepositorier) FindByIdWithVisits(id int) (*repository.Pet, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdWithVisits")
	}

	var r0 *repository.Pet
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*repository.Pet, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *repository.Pet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Pet)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: name
func (_m *PetRepositorier) FindByName(name string) ([]repository.Pet, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 []repository.Pet
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]repository.Pet, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []repository.Pet); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Pet)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: pet
func (_m *PetRepositorier) Insert(pet *repository.Pet) (*repository.Pet, error) {
	ret := _m.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *repository.Pet
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Pet) (*repository.Pet, error)); ok {
		return rf(pet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Pet) *repository.Pet); ok {
		r0 = rf(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Pet)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Pet) error); ok {
		r1 = rf(pet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: pet
func (_m *PetRepositorier) Update(pet *repository.Pet) (*repository.Pet, error) {
	ret := _m.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Pet
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Pet) (*repository.Pet, error)); ok {
		return rf(pet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Pet) *repository.Pet); ok {
		r0 = rf(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Pet)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Pet) error); ok {
		r1 = rf(pet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPetRepositorier creates a new instance of PetRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPetRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *PetRepositorier {
	mock := &PetRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
