// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	visit "fiber-petclinic-service/api/visit"

	mock "github.com/stretchr/testify/mock"
)

// Servicer is an autogenerated mock type for the Servicer type
type Servicer struct {
	mock.Mock
}

// create provides a mock function with given fields: _a0
func (_m *Servicer) create(_a0 *visit.Request) (*visit.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 *visit.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*visit.Request) (*visit.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*visit.Request) *visit.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*visit.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*visit.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getAllVisits provides a mock function with no fields
func (_m *Servicer) getAllVisits() (*visit.Responses, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllVisits")
	}

	var r0 *visit.Responses
	var r1 error
	if rf, ok := ret.Get(0).(func() (*visit.Responses, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *visit.Responses); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*visit.Responses)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getVisitById provides a mock function with given fields: id
func (_m *Servicer) getVisitById(id int) (*visit.Response, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getVisitById")
	}

	var r0 *visit.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*visit.Response, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *visit.Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*visit.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// update provides a mock function with given fields: _a0
func (_m *Servicer) update(_a0 *visit.Request) (*visit.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 *visit.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*visit.Request) (*visit.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*visit.Request) *visit.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*visit.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*visit.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServicer creates a new instance of Servicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Servicer {
	mock := &Servicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
