// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	repository "fiber-petclinic-service/pkg/repository"

	mock "github.com/stretchr/testify/mock"
)

// VetRepositorier is an autogenerated mock type for the VetRepositorier type
type VetRepositorier struct {
	mock.Mock
}

// FindAll provides a mock function with no fields
func (_m *VetRepositorier) FindAll() ([]repository.Vet, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []repository.Vet
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.Vet, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.Vet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Vet)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPreload provides a mock function with no fields
func (_m *VetRepositorier) FindAllPreload() ([]repository.Vet, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllPreload")
	}

	var r0 []repository.Vet
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.Vet, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.Vet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Vet)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllSpecialties provides a mock function with no fields
func (_m *VetRepositorier) FindAllSpecialties() ([]repository.Specialty, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllSpecialties")
	}

	var r0 []repository.Specialty
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.Specialty, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.Specialty); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Specialty)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *VetRepositorier) FindById(id int) (*repository.Vet, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *repository.Vet
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*repository.Vet, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *repository.Vet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Vet)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdWithSpecialties provides a mock function with given fields: id
func (_m *VetRepositorier) FindByIdWithSpecialties(id int) (*repository.Vet, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdWithSpecialties")
	}

	var r0 *repository.Vet
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*repository.Vet, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *repository.Vet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Vet)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByLastName provides a mock function with given fields: lastName
func (_m *VetRepositorier) FindByLastName(lastName string) ([]repository.Vet, error) {
	ret := _m.Called(lastName)

	if len(ret) == 0 {
		panic("no return value specified for FindByLastName")
	}

	var r0 []repository.Vet
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]repository.Vet, error)); ok {
		return rf(lastName)
	}
	if rf, ok := ret.Get(0).(func(string) []repository.Vet); ok {
		r0 = rf(lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Vet)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: vet
func (_m *VetRepositorier) Insert(vet *repository.Vet) (*repository.Vet, error) {
	ret := _m.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *repository.Vet
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Vet) (*repository.Vet, error)); ok {
		return rf(vet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Vet) *repository.Vet); ok {
		r0 = rf(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Vet)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Vet) error); ok {
		r1 = rf(vet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: vet
func (_m *VetRepositorier) Update(vet *repository.Vet) (*repository.Vet, error) {
	ret := _m.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Vet
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Vet) (*repository.Vet, error)); ok {
		return rf(vet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Vet) *repository.Vet); ok {
		r0 = rf(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Vet)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Vet) error); ok {
		r1 = rf(vet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVetRepositorier creates a new instance of VetRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVetRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *VetRepositorier {
	mock := &VetRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
