// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	repository "fiber-petclinic-service/pkg/repository"

	mock "github.com/stretchr/testify/mock"
)

// VisitRepositorier is an autogenerated mock type for the VisitRepositorier type
type VisitRepositorier struct {
	mock.Mock
}

// FindAll provides a mock function with no fields
func (_m *VisitRepositorier) FindAll() ([]repository.Visit, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []repository.Visit
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.Visit, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.Visit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Visit)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *VisitRepositorier) FindById(id int) (*repository.Visit, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *repository.Visit
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*repository.Visit, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *repository.Visit); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Visit)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: visit
func (_m *VisitRepositorier) Insert(visit *repository.Visit) (*repository.Visit, error) {
	ret := _m.Called(visit)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *repository.Visit
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Visit) (*repository.Visit, error)); ok {
		return rf(visit)
	}
	if rf, ok := ret.Get(0).(func(*repository.Visit) *repository.Visit); ok {
		r0 = rf(visit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Visit)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Visit) error); ok {
		r1 = rf(visit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: visit
func (_m *VisitRepositorier) Update(visit *repository.Visit) (*repository.Visit, error) {
	ret := _m.Called(visit)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Visit
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Visit) (*repository.Visit, error)); ok {
		return rf(visit)
	}
	if rf, ok := ret.Get(0).(func(*repository.Visit) *repository.Visit); ok {
		r0 = rf(visit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Visit)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Visit) error); ok {
		r1 = rf(visit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVisitRepositorier creates a new instance of VisitRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitRepositorier {
	mock := &VisitRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
