// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pet

import (
	"fiber-petclinic-service/pkg/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServicer creates a new instance of MockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicer {
	mock := &MockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

type MockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicer) EXPECT() *MockServicer_Expecter {
	return &MockServicer_Expecter{mock: &_m.Mock}
}

// create provides a mock function for the type MockServicer
func (_mock *MockServicer) create(pet *repository.Pet) (*Response, error) {
	ret := _mock.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*repository.Pet) (*Response, error)); ok {
		return returnFunc(pet)
	}
	if returnFunc, ok := ret.Get(0).(func(*repository.Pet) *Response); ok {
		r0 = returnFunc(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*repository.Pet) error); ok {
		r1 = returnFunc(pet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type MockServicer_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - pet *repository.Pet
func (_e *MockServicer_Expecter) create(pet interface{}) *MockServicer_create_Call {
	return &MockServicer_create_Call{Call: _e.mock.On("create", pet)}
}

func (_c *MockServicer_create_Call) Run(run func(pet *repository.Pet)) *MockServicer_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Pet
		if args[0] != nil {
			arg0 = args[0].(*repository.Pet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_create_Call) Return(response *Response, err error) *MockServicer_create_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServicer_create_Call) RunAndReturn(run func(pet *repository.Pet) (*Response, error)) *MockServicer_create_Call {
	_c.Call.Return(run)
	return _c
}

// getAllPets provides a mock function for the type MockServicer
func (_mock *MockServicer) getAllPets() (*Responses, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllPets")
	}

	var r0 *Responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*Responses, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *Responses); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getAllPets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllPets'
type MockServicer_getAllPets_Call struct {
	*mock.Call
}

// getAllPets is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllPets() *MockServicer_getAllPets_Call {
	return &MockServicer_getAllPets_Call{Call: _e.mock.On("getAllPets")}
}

func (_c *MockServicer_getAllPets_Call) Run(run func()) *MockServicer_getAllPets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllPets_Call) Return(responses *Responses, err error) *MockServicer_getAllPets_Call {
	_c.Call.Return(responses, err)
	return _c
}

func (_c *MockServicer_getAllPets_Call) RunAndReturn(run func() (*Responses, error)) *MockServicer_getAllPets_Call {
	_c.Call.Return(run)
	return _c
}

// getPetById provides a mock function for the type MockServicer
func (_mock *MockServicer) getPetById(id uint) (*Response, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getPetById")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Response, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Response); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getPetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPetById'
type MockServicer_getPetById_Call struct {
	*mock.Call
}

// getPetById is a helper method to define mock.On call
//   - id uint
func (_e *MockServicer_Expecter) getPetById(id interface{}) *MockServicer_getPetById_Call {
	return &MockServicer_getPetById_Call{Call: _e.mock.On("getPetById", id)}
}

func (_c *MockServicer_getPetById_Call) Run(run func(id uint)) *MockServicer_getPetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getPetById_Call) Return(response *Response, err error) *MockServicer_getPetById_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServicer_getPetById_Call) RunAndReturn(run func(id uint) (*Response, error)) *MockServicer_getPetById_Call {
	_c.Call.Return(run)
	return _c
}

// getPetWithVisitsById provides a mock function for the type MockServicer
func (_mock *MockServicer) getPetWithVisitsById(id uint) (*Response, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getPetWithVisitsById")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Response, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Response); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getPetWithVisitsById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPetWithVisitsById'
type MockServicer_getPetWithVisitsById_Call struct {
	*mock.Call
}

// getPetWithVisitsById is a helper method to define mock.On call
//   - id uint
func (_e *MockServicer_Expecter) getPetWithVisitsById(id interface{}) *MockServicer_getPetWithVisitsById_Call {
	return &MockServicer_getPetWithVisitsById_Call{Call: _e.mock.On("getPetWithVisitsById", id)}
}

func (_c *MockServicer_getPetWithVisitsById_Call) Run(run func(id uint)) *MockServicer_getPetWithVisitsById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getPetWithVisitsById_Call) Return(response *Response, err error) *MockServicer_getPetWithVisitsById_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServicer_getPetWithVisitsById_Call) RunAndReturn(run func(id uint) (*Response, error)) *MockServicer_getPetWithVisitsById_Call {
	_c.Call.Return(run)
	return _c
}

// getPetsByName provides a mock function for the type MockServicer
func (_mock *MockServicer) getPetsByName(name string) (*Responses, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for getPetsByName")
	}

	var r0 *Responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Responses, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Responses); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getPetsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPetsByName'
type MockServicer_getPetsByName_Call struct {
	*mock.Call
}

// getPetsByName is a helper method to define mock.On call
//   - name string
func (_e *MockServicer_Expecter) getPetsByName(name interface{}) *MockServicer_getPetsByName_Call {
	return &MockServicer_getPetsByName_Call{Call: _e.mock.On("getPetsByName", name)}
}

func (_c *MockServicer_getPetsByName_Call) Run(run func(name string)) *MockServicer_getPetsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getPetsByName_Call) Return(responses *Responses, err error) *MockServicer_getPetsByName_Call {
	_c.Call.Return(responses, err)
	return _c
}

func (_c *MockServicer_getPetsByName_Call) RunAndReturn(run func(name string) (*Responses, error)) *MockServicer_getPetsByName_Call {
	_c.Call.Return(run)
	return _c
}

// update provides a mock function for the type MockServicer
func (_mock *MockServicer) update(pet *repository.Pet) (*Response, error) {
	ret := _mock.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*repository.Pet) (*Response, error)); ok {
		return returnFunc(pet)
	}
	if returnFunc, ok := ret.Get(0).(func(*repository.Pet) *Response); ok {
		r0 = returnFunc(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*repository.Pet) error); ok {
		r1 = returnFunc(pet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'update'
type MockServicer_update_Call struct {
	*mock.Call
}

// update is a helper method to define mock.On call
//   - pet *repository.Pet
func (_e *MockServicer_Expecter) update(pet interface{}) *MockServicer_update_Call {
	return &MockServicer_update_Call{Call: _e.mock.On("update", pet)}
}

func (_c *MockServicer_update_Call) Run(run func(pet *repository.Pet)) *MockServicer_update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Pet
		if args[0] != nil {
			arg0 = args[0].(*repository.Pet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_update_Call) Return(response *Response, err error) *MockServicer_update_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServicer_update_Call) RunAndReturn(run func(pet *repository.Pet) (*Response, error)) *MockServicer_update_Call {
	_c.Call.Return(run)
	return _c
}
