// Code generated by mockery v2.42.2. DO NOT EDIT.

package vet

import (
	repository "github.com/rhtran/gin-petclinic-service/pkg/infra/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockServicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

type MockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicer) EXPECT() *MockServicer_Expecter {
	return &MockServicer_Expecter{mock: &_m.Mock}
}

// create provides a mock function with given fields: vet
func (_m *MockServicer) create(vet *repository.Vet) (*Response, error) {
	ret := _m.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Vet) (*Response, error)); ok {
		return rf(vet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Vet) *Response); ok {
		r0 = rf(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Vet) error); ok {
		r1 = rf(vet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type MockServicer_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - vet *repository.Vet
func (_e *MockServicer_Expecter) create(vet interface{}) *MockServicer_create_Call {
	return &MockServicer_create_Call{Call: _e.mock.On("create", vet)}
}

func (_c *MockServicer_create_Call) Run(run func(vet *repository.Vet)) *MockServicer_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*repository.Vet))
	})
	return _c
}

func (_c *MockServicer_create_Call) Return(_a0 *Response, _a1 error) *MockServicer_create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_create_Call) RunAndReturn(run func(*repository.Vet) (*Response, error)) *MockServicer_create_Call {
	_c.Call.Return(run)
	return _c
}

// getAllSpecialties provides a mock function with given fields:
func (_m *MockServicer) getAllSpecialties() (*specialtiesResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllSpecialties")
	}

	var r0 *specialtiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*specialtiesResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *specialtiesResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*specialtiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getAllSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllSpecialties'
type MockServicer_getAllSpecialties_Call struct {
	*mock.Call
}

// getAllSpecialties is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllSpecialties() *MockServicer_getAllSpecialties_Call {
	return &MockServicer_getAllSpecialties_Call{Call: _e.mock.On("getAllSpecialties")}
}

func (_c *MockServicer_getAllSpecialties_Call) Run(run func()) *MockServicer_getAllSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllSpecialties_Call) Return(_a0 *specialtiesResponse, _a1 error) *MockServicer_getAllSpecialties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getAllSpecialties_Call) RunAndReturn(run func() (*specialtiesResponse, error)) *MockServicer_getAllSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// getAllVets provides a mock function with given fields:
func (_m *MockServicer) getAllVets() ([]Response, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllVets")
	}

	var r0 []Response
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]Response, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Response)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getAllVets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllVets'
type MockServicer_getAllVets_Call struct {
	*mock.Call
}

// getAllVets is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllVets() *MockServicer_getAllVets_Call {
	return &MockServicer_getAllVets_Call{Call: _e.mock.On("getAllVets")}
}

func (_c *MockServicer_getAllVets_Call) Run(run func()) *MockServicer_getAllVets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllVets_Call) Return(_a0 []Response, _a1 error) *MockServicer_getAllVets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getAllVets_Call) RunAndReturn(run func() ([]Response, error)) *MockServicer_getAllVets_Call {
	_c.Call.Return(run)
	return _c
}

// getAllVetsWithSpecialties provides a mock function with given fields:
func (_m *MockServicer) getAllVetsWithSpecialties() ([]Response, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllVetsWithSpecialties")
	}

	var r0 []Response
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]Response, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Response)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getAllVetsWithSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllVetsWithSpecialties'
type MockServicer_getAllVetsWithSpecialties_Call struct {
	*mock.Call
}

// getAllVetsWithSpecialties is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllVetsWithSpecialties() *MockServicer_getAllVetsWithSpecialties_Call {
	return &MockServicer_getAllVetsWithSpecialties_Call{Call: _e.mock.On("getAllVetsWithSpecialties")}
}

func (_c *MockServicer_getAllVetsWithSpecialties_Call) Run(run func()) *MockServicer_getAllVetsWithSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllVetsWithSpecialties_Call) Return(_a0 []Response, _a1 error) *MockServicer_getAllVetsWithSpecialties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getAllVetsWithSpecialties_Call) RunAndReturn(run func() ([]Response, error)) *MockServicer_getAllVetsWithSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// getVetById provides a mock function with given fields: id
func (_m *MockServicer) getVetById(id int) (*Response, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getVetById")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*Response, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getVetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getVetById'
type MockServicer_getVetById_Call struct {
	*mock.Call
}

// getVetById is a helper method to define mock.On call
//   - id int
func (_e *MockServicer_Expecter) getVetById(id interface{}) *MockServicer_getVetById_Call {
	return &MockServicer_getVetById_Call{Call: _e.mock.On("getVetById", id)}
}

func (_c *MockServicer_getVetById_Call) Run(run func(id int)) *MockServicer_getVetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockServicer_getVetById_Call) Return(_a0 *Response, _a1 error) *MockServicer_getVetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getVetById_Call) RunAndReturn(run func(int) (*Response, error)) *MockServicer_getVetById_Call {
	_c.Call.Return(run)
	return _c
}

// getVetByIdWithSpecialties provides a mock function with given fields: id
func (_m *MockServicer) getVetByIdWithSpecialties(id int) (*Response, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getVetByIdWithSpecialties")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*Response, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getVetByIdWithSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getVetByIdWithSpecialties'
type MockServicer_getVetByIdWithSpecialties_Call struct {
	*mock.Call
}

// getVetByIdWithSpecialties is a helper method to define mock.On call
//   - id int
func (_e *MockServicer_Expecter) getVetByIdWithSpecialties(id interface{}) *MockServicer_getVetByIdWithSpecialties_Call {
	return &MockServicer_getVetByIdWithSpecialties_Call{Call: _e.mock.On("getVetByIdWithSpecialties", id)}
}

func (_c *MockServicer_getVetByIdWithSpecialties_Call) Run(run func(id int)) *MockServicer_getVetByIdWithSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockServicer_getVetByIdWithSpecialties_Call) Return(_a0 *Response, _a1 error) *MockServicer_getVetByIdWithSpecialties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getVetByIdWithSpecialties_Call) RunAndReturn(run func(int) (*Response, error)) *MockServicer_getVetByIdWithSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// getVetByLastName provides a mock function with given fields: lastName
func (_m *MockServicer) getVetByLastName(lastName string) ([]Response, error) {
	ret := _m.Called(lastName)

	if len(ret) == 0 {
		panic("no return value specified for getVetByLastName")
	}

	var r0 []Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]Response, error)); ok {
		return rf(lastName)
	}
	if rf, ok := ret.Get(0).(func(string) []Response); ok {
		r0 = rf(lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_getVetByLastName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getVetByLastName'
type MockServicer_getVetByLastName_Call struct {
	*mock.Call
}

// getVetByLastName is a helper method to define mock.On call
//   - lastName string
func (_e *MockServicer_Expecter) getVetByLastName(lastName interface{}) *MockServicer_getVetByLastName_Call {
	return &MockServicer_getVetByLastName_Call{Call: _e.mock.On("getVetByLastName", lastName)}
}

func (_c *MockServicer_getVetByLastName_Call) Run(run func(lastName string)) *MockServicer_getVetByLastName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServicer_getVetByLastName_Call) Return(_a0 []Response, _a1 error) *MockServicer_getVetByLastName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_getVetByLastName_Call) RunAndReturn(run func(string) ([]Response, error)) *MockServicer_getVetByLastName_Call {
	_c.Call.Return(run)
	return _c
}

// update provides a mock function with given fields: vet
func (_m *MockServicer) update(vet *repository.Vet) (*Response, error) {
	ret := _m.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.Vet) (*Response, error)); ok {
		return rf(vet)
	}
	if rf, ok := ret.Get(0).(func(*repository.Vet) *Response); ok {
		r0 = rf(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.Vet) error); ok {
		r1 = rf(vet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicer_update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'update'
type MockServicer_update_Call struct {
	*mock.Call
}

// update is a helper method to define mock.On call
//   - vet *repository.Vet
func (_e *MockServicer_Expecter) update(vet interface{}) *MockServicer_update_Call {
	return &MockServicer_update_Call{Call: _e.mock.On("update", vet)}
}

func (_c *MockServicer_update_Call) Run(run func(vet *repository.Vet)) *MockServicer_update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*repository.Vet))
	})
	return _c
}

func (_c *MockServicer_update_Call) Return(_a0 *Response, _a1 error) *MockServicer_update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicer_update_Call) RunAndReturn(run func(*repository.Vet) (*Response, error)) *MockServicer_update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServicer creates a new instance of MockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicer {
	mock := &MockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
