// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbase

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Connect(context1 context.Context) (*gorm.DB, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 *gorm.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDatabase_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockDatabase_Expecter) Connect(context1 interface{}) *MockDatabase_Connect_Call {
	return &MockDatabase_Connect_Call{Call: _e.mock.On("Connect", context1)}
}

func (_c *MockDatabase_Connect_Call) Run(run func(context1 context.Context)) *MockDatabase_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_Connect_Call) Return(dB *gorm.DB, err error) *MockDatabase_Connect_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *MockDatabase_Connect_Call) RunAndReturn(run func(context1 context.Context) (*gorm.DB, error)) *MockDatabase_Connect_Call {
	_c.Call.Return(run)
	return _c
}
