appInfo:
  name: "fiber3-petclinic-service"
  description: "Pet Clinic Web Application using Fiber"
  version: "1.0.0"

circuitBreaker:
  failureThreshold: 3
  timeout: 5
  successThreshold: 2

databases:
  sqlite:
    driver: sqlite3
    host: localhost
    name: pet-clinic.sqlite
    connectionPool:
      maxOpenConnections: 10
      maxIdleConnections: 5
      maxIdleTime: 30
#  postgres:
#    driver: postgres
#    host: localhost
#    port: 5432
#    username: pet_user
    # in production, use environment variables for sensitive data
    # e.g., DATABASES_POSTGRES_PASSWORD
#    password: pet_user
#    name: pet_clinic
#    sslMode: disable
#    connectionPool:
#      maxOpenConnections: 25
#      maxIdleConnections: 25
#      maxIdleTime: 15

gorm:
  # logLevel - silent(1), error(2), warn(3), info(4))
  logLevel: 2
  singularTable: false

server:
  baseURL: "/api/pet-clinic"
  host: localhost
  enablePrefork: false
  certFile: "cmd/certs/myCA.pem"
  keyFile: "cmd/certs/myCA-without-passphrase.key"
  httpPort: ":8092"
  enableCompression: true
  # LevelDisabled(-1), LevelDefault(0), LevelBestSpeed(1), LevelBestCompression(2)
  compressionLevel: 2
  logLevel: "info"
