// Code generated by mockery v2.52.2. DO NOT EDIT.

package dbase

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// PgConnect provides a mock function with no fields
func (_m *MockDatabase) PgConnect() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PgConnect")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// MockDatabase_PgConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PgConnect'
type MockDatabase_PgConnect_Call struct {
	*mock.Call
}

// PgConnect is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) PgConnect() *MockDatabase_PgConnect_Call {
	return &MockDatabase_PgConnect_Call{Call: _e.mock.On("PgConnect")}
}

func (_c *MockDatabase_PgConnect_Call) Run(run func()) *MockDatabase_PgConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_PgConnect_Call) Return(_a0 *gorm.DB) *MockDatabase_PgConnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_PgConnect_Call) RunAndReturn(run func() *gorm.DB) *MockDatabase_PgConnect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
