// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package visit

import (
	"fiber3-petclinic-service/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServicer creates a new instance of MockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicer {
	mock := &MockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

type MockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicer) EXPECT() *MockServicer_Expecter {
	return &MockServicer_Expecter{mock: &_m.Mock}
}

// create provides a mock function for the type MockServicer
func (_mock *MockServicer) create(visit *repository.Visit) (*response, error) {
	ret := _mock.Called(visit)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*repository.Visit) (*response, error)); ok {
		return returnFunc(visit)
	}
	if returnFunc, ok := ret.Get(0).(func(*repository.Visit) *response); ok {
		r0 = returnFunc(visit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*repository.Visit) error); ok {
		r1 = returnFunc(visit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type MockServicer_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - visit *repository.Visit
func (_e *MockServicer_Expecter) create(visit interface{}) *MockServicer_create_Call {
	return &MockServicer_create_Call{Call: _e.mock.On("create", visit)}
}

func (_c *MockServicer_create_Call) Run(run func(visit *repository.Visit)) *MockServicer_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Visit
		if args[0] != nil {
			arg0 = args[0].(*repository.Visit)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_create_Call) Return(responseMoqParam *response, err error) *MockServicer_create_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_create_Call) RunAndReturn(run func(visit *repository.Visit) (*response, error)) *MockServicer_create_Call {
	_c.Call.Return(run)
	return _c
}

// getAllVisits provides a mock function for the type MockServicer
func (_mock *MockServicer) getAllVisits() (*responses, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllVisits")
	}

	var r0 *responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*responses, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *responses); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getAllVisits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllVisits'
type MockServicer_getAllVisits_Call struct {
	*mock.Call
}

// getAllVisits is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllVisits() *MockServicer_getAllVisits_Call {
	return &MockServicer_getAllVisits_Call{Call: _e.mock.On("getAllVisits")}
}

func (_c *MockServicer_getAllVisits_Call) Run(run func()) *MockServicer_getAllVisits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllVisits_Call) Return(responsesMoqParam *responses, err error) *MockServicer_getAllVisits_Call {
	_c.Call.Return(responsesMoqParam, err)
	return _c
}

func (_c *MockServicer_getAllVisits_Call) RunAndReturn(run func() (*responses, error)) *MockServicer_getAllVisits_Call {
	_c.Call.Return(run)
	return _c
}

// getVisitById provides a mock function for the type MockServicer
func (_mock *MockServicer) getVisitById(id uint) (*response, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getVisitById")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*response, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *response); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getVisitById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getVisitById'
type MockServicer_getVisitById_Call struct {
	*mock.Call
}

// getVisitById is a helper method to define mock.On call
//   - id uint
func (_e *MockServicer_Expecter) getVisitById(id interface{}) *MockServicer_getVisitById_Call {
	return &MockServicer_getVisitById_Call{Call: _e.mock.On("getVisitById", id)}
}

func (_c *MockServicer_getVisitById_Call) Run(run func(id uint)) *MockServicer_getVisitById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getVisitById_Call) Return(responseMoqParam *response, err error) *MockServicer_getVisitById_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_getVisitById_Call) RunAndReturn(run func(id uint) (*response, error)) *MockServicer_getVisitById_Call {
	_c.Call.Return(run)
	return _c
}

// update provides a mock function for the type MockServicer
func (_mock *MockServicer) update(visit *repository.Visit) (*response, error) {
	ret := _mock.Called(visit)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*repository.Visit) (*response, error)); ok {
		return returnFunc(visit)
	}
	if returnFunc, ok := ret.Get(0).(func(*repository.Visit) *response); ok {
		r0 = returnFunc(visit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*repository.Visit) error); ok {
		r1 = returnFunc(visit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'update'
type MockServicer_update_Call struct {
	*mock.Call
}

// update is a helper method to define mock.On call
//   - visit *repository.Visit
func (_e *MockServicer_Expecter) update(visit interface{}) *MockServicer_update_Call {
	return &MockServicer_update_Call{Call: _e.mock.On("update", visit)}
}

func (_c *MockServicer_update_Call) Run(run func(visit *repository.Visit)) *MockServicer_update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Visit
		if args[0] != nil {
			arg0 = args[0].(*repository.Visit)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_update_Call) Return(responseMoqParam *response, err error) *MockServicer_update_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_update_Call) RunAndReturn(run func(visit *repository.Visit) (*response, error)) *MockServicer_update_Call {
	_c.Call.Return(run)
	return _c
}
