// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vet

import (
	"gin-petclinic-service/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServicer creates a new instance of MockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicer {
	mock := &MockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

type MockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicer) EXPECT() *MockServicer_Expecter {
	return &MockServicer_Expecter{mock: &_m.Mock}
}

// create provides a mock function for the type MockServicer
func (_mock *MockServicer) create(vet *repository.Vet) (*response, error) {
	ret := _mock.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*repository.Vet) (*response, error)); ok {
		return returnFunc(vet)
	}
	if returnFunc, ok := ret.Get(0).(func(*repository.Vet) *response); ok {
		r0 = returnFunc(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*repository.Vet) error); ok {
		r1 = returnFunc(vet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type MockServicer_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - vet *repository.Vet
func (_e *MockServicer_Expecter) create(vet interface{}) *MockServicer_create_Call {
	return &MockServicer_create_Call{Call: _e.mock.On("create", vet)}
}

func (_c *MockServicer_create_Call) Run(run func(vet *repository.Vet)) *MockServicer_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Vet
		if args[0] != nil {
			arg0 = args[0].(*repository.Vet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_create_Call) Return(responseMoqParam *response, err error) *MockServicer_create_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_create_Call) RunAndReturn(run func(vet *repository.Vet) (*response, error)) *MockServicer_create_Call {
	_c.Call.Return(run)
	return _c
}

// getAllSpecialties provides a mock function for the type MockServicer
func (_mock *MockServicer) getAllSpecialties() (*specialtiesResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllSpecialties")
	}

	var r0 *specialtiesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*specialtiesResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *specialtiesResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*specialtiesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getAllSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllSpecialties'
type MockServicer_getAllSpecialties_Call struct {
	*mock.Call
}

// getAllSpecialties is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllSpecialties() *MockServicer_getAllSpecialties_Call {
	return &MockServicer_getAllSpecialties_Call{Call: _e.mock.On("getAllSpecialties")}
}

func (_c *MockServicer_getAllSpecialties_Call) Run(run func()) *MockServicer_getAllSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllSpecialties_Call) Return(specialtiesResponseMoqParam *specialtiesResponse, err error) *MockServicer_getAllSpecialties_Call {
	_c.Call.Return(specialtiesResponseMoqParam, err)
	return _c
}

func (_c *MockServicer_getAllSpecialties_Call) RunAndReturn(run func() (*specialtiesResponse, error)) *MockServicer_getAllSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// getAllVets provides a mock function for the type MockServicer
func (_mock *MockServicer) getAllVets() (*responses, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllVets")
	}

	var r0 *responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*responses, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *responses); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getAllVets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllVets'
type MockServicer_getAllVets_Call struct {
	*mock.Call
}

// getAllVets is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllVets() *MockServicer_getAllVets_Call {
	return &MockServicer_getAllVets_Call{Call: _e.mock.On("getAllVets")}
}

func (_c *MockServicer_getAllVets_Call) Run(run func()) *MockServicer_getAllVets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllVets_Call) Return(responsesMoqParam *responses, err error) *MockServicer_getAllVets_Call {
	_c.Call.Return(responsesMoqParam, err)
	return _c
}

func (_c *MockServicer_getAllVets_Call) RunAndReturn(run func() (*responses, error)) *MockServicer_getAllVets_Call {
	_c.Call.Return(run)
	return _c
}

// getAllVetsWithSpecialties provides a mock function for the type MockServicer
func (_mock *MockServicer) getAllVetsWithSpecialties() (*responses, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllVetsWithSpecialties")
	}

	var r0 *responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*responses, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *responses); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getAllVetsWithSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllVetsWithSpecialties'
type MockServicer_getAllVetsWithSpecialties_Call struct {
	*mock.Call
}

// getAllVetsWithSpecialties is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllVetsWithSpecialties() *MockServicer_getAllVetsWithSpecialties_Call {
	return &MockServicer_getAllVetsWithSpecialties_Call{Call: _e.mock.On("getAllVetsWithSpecialties")}
}

func (_c *MockServicer_getAllVetsWithSpecialties_Call) Run(run func()) *MockServicer_getAllVetsWithSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllVetsWithSpecialties_Call) Return(responsesMoqParam *responses, err error) *MockServicer_getAllVetsWithSpecialties_Call {
	_c.Call.Return(responsesMoqParam, err)
	return _c
}

func (_c *MockServicer_getAllVetsWithSpecialties_Call) RunAndReturn(run func() (*responses, error)) *MockServicer_getAllVetsWithSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// getVetById provides a mock function for the type MockServicer
func (_mock *MockServicer) getVetById(id uint) (*response, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getVetById")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*response, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *response); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getVetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getVetById'
type MockServicer_getVetById_Call struct {
	*mock.Call
}

// getVetById is a helper method to define mock.On call
//   - id uint
func (_e *MockServicer_Expecter) getVetById(id interface{}) *MockServicer_getVetById_Call {
	return &MockServicer_getVetById_Call{Call: _e.mock.On("getVetById", id)}
}

func (_c *MockServicer_getVetById_Call) Run(run func(id uint)) *MockServicer_getVetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getVetById_Call) Return(responseMoqParam *response, err error) *MockServicer_getVetById_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_getVetById_Call) RunAndReturn(run func(id uint) (*response, error)) *MockServicer_getVetById_Call {
	_c.Call.Return(run)
	return _c
}

// getVetByIdWithSpecialties provides a mock function for the type MockServicer
func (_mock *MockServicer) getVetByIdWithSpecialties(id uint) (*response, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getVetByIdWithSpecialties")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*response, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *response); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getVetByIdWithSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getVetByIdWithSpecialties'
type MockServicer_getVetByIdWithSpecialties_Call struct {
	*mock.Call
}

// getVetByIdWithSpecialties is a helper method to define mock.On call
//   - id uint
func (_e *MockServicer_Expecter) getVetByIdWithSpecialties(id interface{}) *MockServicer_getVetByIdWithSpecialties_Call {
	return &MockServicer_getVetByIdWithSpecialties_Call{Call: _e.mock.On("getVetByIdWithSpecialties", id)}
}

func (_c *MockServicer_getVetByIdWithSpecialties_Call) Run(run func(id uint)) *MockServicer_getVetByIdWithSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getVetByIdWithSpecialties_Call) Return(responseMoqParam *response, err error) *MockServicer_getVetByIdWithSpecialties_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_getVetByIdWithSpecialties_Call) RunAndReturn(run func(id uint) (*response, error)) *MockServicer_getVetByIdWithSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// getVetByLastName provides a mock function for the type MockServicer
func (_mock *MockServicer) getVetByLastName(lastName string) (*responses, error) {
	ret := _mock.Called(lastName)

	if len(ret) == 0 {
		panic("no return value specified for getVetByLastName")
	}

	var r0 *responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*responses, error)); ok {
		return returnFunc(lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *responses); ok {
		r0 = returnFunc(lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getVetByLastName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getVetByLastName'
type MockServicer_getVetByLastName_Call struct {
	*mock.Call
}

// getVetByLastName is a helper method to define mock.On call
//   - lastName string
func (_e *MockServicer_Expecter) getVetByLastName(lastName interface{}) *MockServicer_getVetByLastName_Call {
	return &MockServicer_getVetByLastName_Call{Call: _e.mock.On("getVetByLastName", lastName)}
}

func (_c *MockServicer_getVetByLastName_Call) Run(run func(lastName string)) *MockServicer_getVetByLastName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getVetByLastName_Call) Return(responsesMoqParam *responses, err error) *MockServicer_getVetByLastName_Call {
	_c.Call.Return(responsesMoqParam, err)
	return _c
}

func (_c *MockServicer_getVetByLastName_Call) RunAndReturn(run func(lastName string) (*responses, error)) *MockServicer_getVetByLastName_Call {
	_c.Call.Return(run)
	return _c
}

// update provides a mock function for the type MockServicer
func (_mock *MockServicer) update(vet *repository.Vet) (*response, error) {
	ret := _mock.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*repository.Vet) (*response, error)); ok {
		return returnFunc(vet)
	}
	if returnFunc, ok := ret.Get(0).(func(*repository.Vet) *response); ok {
		r0 = returnFunc(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*repository.Vet) error); ok {
		r1 = returnFunc(vet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'update'
type MockServicer_update_Call struct {
	*mock.Call
}

// update is a helper method to define mock.On call
//   - vet *repository.Vet
func (_e *MockServicer_Expecter) update(vet interface{}) *MockServicer_update_Call {
	return &MockServicer_update_Call{Call: _e.mock.On("update", vet)}
}

func (_c *MockServicer_update_Call) Run(run func(vet *repository.Vet)) *MockServicer_update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Vet
		if args[0] != nil {
			arg0 = args[0].(*repository.Vet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_update_Call) Return(responseMoqParam *response, err error) *MockServicer_update_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockServicer_update_Call) RunAndReturn(run func(vet *repository.Vet) (*response, error)) *MockServicer_update_Call {
	_c.Call.Return(run)
	return _c
}
