// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOwnerRepositorier creates a new instance of MockOwnerRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOwnerRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOwnerRepositorier {
	mock := &MockOwnerRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOwnerRepositorier is an autogenerated mock type for the OwnerRepositorier type
type MockOwnerRepositorier struct {
	mock.Mock
}

type MockOwnerRepositorier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOwnerRepositorier) EXPECT() *MockOwnerRepositorier_Expecter {
	return &MockOwnerRepositorier_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockOwnerRepositorier
func (_mock *MockOwnerRepositorier) FindAll() ([]Owner, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []Owner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Owner, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Owner); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Owner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerRepositorier_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockOwnerRepositorier_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockOwnerRepositorier_Expecter) FindAll() *MockOwnerRepositorier_FindAll_Call {
	return &MockOwnerRepositorier_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockOwnerRepositorier_FindAll_Call) Run(run func()) *MockOwnerRepositorier_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOwnerRepositorier_FindAll_Call) Return(owners []Owner, err error) *MockOwnerRepositorier_FindAll_Call {
	_c.Call.Return(owners, err)
	return _c
}

func (_c *MockOwnerRepositorier_FindAll_Call) RunAndReturn(run func() ([]Owner, error)) *MockOwnerRepositorier_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockOwnerRepositorier
func (_mock *MockOwnerRepositorier) FindById(id uint) (*Owner, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *Owner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Owner, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Owner); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Owner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerRepositorier_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockOwnerRepositorier_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uint
func (_e *MockOwnerRepositorier_Expecter) FindById(id interface{}) *MockOwnerRepositorier_FindById_Call {
	return &MockOwnerRepositorier_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockOwnerRepositorier_FindById_Call) Run(run func(id uint)) *MockOwnerRepositorier_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOwnerRepositorier_FindById_Call) Return(owner *Owner, err error) *MockOwnerRepositorier_FindById_Call {
	_c.Call.Return(owner, err)
	return _c
}

func (_c *MockOwnerRepositorier_FindById_Call) RunAndReturn(run func(id uint) (*Owner, error)) *MockOwnerRepositorier_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdWithPets provides a mock function for the type MockOwnerRepositorier
func (_mock *MockOwnerRepositorier) FindByIdWithPets(id uint) (*Owner, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdWithPets")
	}

	var r0 *Owner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Owner, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Owner); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Owner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerRepositorier_FindByIdWithPets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdWithPets'
type MockOwnerRepositorier_FindByIdWithPets_Call struct {
	*mock.Call
}

// FindByIdWithPets is a helper method to define mock.On call
//   - id uint
func (_e *MockOwnerRepositorier_Expecter) FindByIdWithPets(id interface{}) *MockOwnerRepositorier_FindByIdWithPets_Call {
	return &MockOwnerRepositorier_FindByIdWithPets_Call{Call: _e.mock.On("FindByIdWithPets", id)}
}

func (_c *MockOwnerRepositorier_FindByIdWithPets_Call) Run(run func(id uint)) *MockOwnerRepositorier_FindByIdWithPets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOwnerRepositorier_FindByIdWithPets_Call) Return(owner *Owner, err error) *MockOwnerRepositorier_FindByIdWithPets_Call {
	_c.Call.Return(owner, err)
	return _c
}

func (_c *MockOwnerRepositorier_FindByIdWithPets_Call) RunAndReturn(run func(id uint) (*Owner, error)) *MockOwnerRepositorier_FindByIdWithPets_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLastName provides a mock function for the type MockOwnerRepositorier
func (_mock *MockOwnerRepositorier) FindByLastName(lastName string) ([]Owner, error) {
	ret := _mock.Called(lastName)

	if len(ret) == 0 {
		panic("no return value specified for FindByLastName")
	}

	var r0 []Owner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]Owner, error)); ok {
		return returnFunc(lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []Owner); ok {
		r0 = returnFunc(lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Owner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerRepositorier_FindByLastName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLastName'
type MockOwnerRepositorier_FindByLastName_Call struct {
	*mock.Call
}

// FindByLastName is a helper method to define mock.On call
//   - lastName string
func (_e *MockOwnerRepositorier_Expecter) FindByLastName(lastName interface{}) *MockOwnerRepositorier_FindByLastName_Call {
	return &MockOwnerRepositorier_FindByLastName_Call{Call: _e.mock.On("FindByLastName", lastName)}
}

func (_c *MockOwnerRepositorier_FindByLastName_Call) Run(run func(lastName string)) *MockOwnerRepositorier_FindByLastName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOwnerRepositorier_FindByLastName_Call) Return(owners []Owner, err error) *MockOwnerRepositorier_FindByLastName_Call {
	_c.Call.Return(owners, err)
	return _c
}

func (_c *MockOwnerRepositorier_FindByLastName_Call) RunAndReturn(run func(lastName string) ([]Owner, error)) *MockOwnerRepositorier_FindByLastName_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockOwnerRepositorier
func (_mock *MockOwnerRepositorier) Insert(owner *Owner) (*Owner, error) {
	ret := _mock.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *Owner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Owner) (*Owner, error)); ok {
		return returnFunc(owner)
	}
	if returnFunc, ok := ret.Get(0).(func(*Owner) *Owner); ok {
		r0 = returnFunc(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Owner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Owner) error); ok {
		r1 = returnFunc(owner)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerRepositorier_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockOwnerRepositorier_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - owner *Owner
func (_e *MockOwnerRepositorier_Expecter) Insert(owner interface{}) *MockOwnerRepositorier_Insert_Call {
	return &MockOwnerRepositorier_Insert_Call{Call: _e.mock.On("Insert", owner)}
}

func (_c *MockOwnerRepositorier_Insert_Call) Run(run func(owner *Owner)) *MockOwnerRepositorier_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Owner
		if args[0] != nil {
			arg0 = args[0].(*Owner)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOwnerRepositorier_Insert_Call) Return(owner1 *Owner, err error) *MockOwnerRepositorier_Insert_Call {
	_c.Call.Return(owner1, err)
	return _c
}

func (_c *MockOwnerRepositorier_Insert_Call) RunAndReturn(run func(owner *Owner) (*Owner, error)) *MockOwnerRepositorier_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOwnerRepositorier
func (_mock *MockOwnerRepositorier) Update(owner *Owner) (*Owner, error) {
	ret := _mock.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Owner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Owner) (*Owner, error)); ok {
		return returnFunc(owner)
	}
	if returnFunc, ok := ret.Get(0).(func(*Owner) *Owner); ok {
		r0 = returnFunc(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Owner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Owner) error); ok {
		r1 = returnFunc(owner)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerRepositorier_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOwnerRepositorier_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - owner *Owner
func (_e *MockOwnerRepositorier_Expecter) Update(owner interface{}) *MockOwnerRepositorier_Update_Call {
	return &MockOwnerRepositorier_Update_Call{Call: _e.mock.On("Update", owner)}
}

func (_c *MockOwnerRepositorier_Update_Call) Run(run func(owner *Owner)) *MockOwnerRepositorier_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Owner
		if args[0] != nil {
			arg0 = args[0].(*Owner)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOwnerRepositorier_Update_Call) Return(owner1 *Owner, err error) *MockOwnerRepositorier_Update_Call {
	_c.Call.Return(owner1, err)
	return _c
}

func (_c *MockOwnerRepositorier_Update_Call) RunAndReturn(run func(owner *Owner) (*Owner, error)) *MockOwnerRepositorier_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPetRepositorier creates a new instance of MockPetRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetRepositorier {
	mock := &MockPetRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetRepositorier is an autogenerated mock type for the PetRepositorier type
type MockPetRepositorier struct {
	mock.Mock
}

type MockPetRepositorier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetRepositorier) EXPECT() *MockPetRepositorier_Expecter {
	return &MockPetRepositorier_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockPetRepositorier
func (_mock *MockPetRepositorier) FindAll() ([]Pet, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Pet, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Pet); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetRepositorier_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPetRepositorier_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockPetRepositorier_Expecter) FindAll() *MockPetRepositorier_FindAll_Call {
	return &MockPetRepositorier_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockPetRepositorier_FindAll_Call) Run(run func()) *MockPetRepositorier_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPetRepositorier_FindAll_Call) Return(pets []Pet, err error) *MockPetRepositorier_FindAll_Call {
	_c.Call.Return(pets, err)
	return _c
}

func (_c *MockPetRepositorier_FindAll_Call) RunAndReturn(run func() ([]Pet, error)) *MockPetRepositorier_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockPetRepositorier
func (_mock *MockPetRepositorier) FindById(id int) (*Pet, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*Pet, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *Pet); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetRepositorier_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockPetRepositorier_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id int
func (_e *MockPetRepositorier_Expecter) FindById(id interface{}) *MockPetRepositorier_FindById_Call {
	return &MockPetRepositorier_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockPetRepositorier_FindById_Call) Run(run func(id int)) *MockPetRepositorier_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPetRepositorier_FindById_Call) Return(pet *Pet, err error) *MockPetRepositorier_FindById_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetRepositorier_FindById_Call) RunAndReturn(run func(id int) (*Pet, error)) *MockPetRepositorier_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdWithVisits provides a mock function for the type MockPetRepositorier
func (_mock *MockPetRepositorier) FindByIdWithVisits(id int) (*Pet, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdWithVisits")
	}

	var r0 *Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*Pet, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *Pet); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetRepositorier_FindByIdWithVisits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdWithVisits'
type MockPetRepositorier_FindByIdWithVisits_Call struct {
	*mock.Call
}

// FindByIdWithVisits is a helper method to define mock.On call
//   - id int
func (_e *MockPetRepositorier_Expecter) FindByIdWithVisits(id interface{}) *MockPetRepositorier_FindByIdWithVisits_Call {
	return &MockPetRepositorier_FindByIdWithVisits_Call{Call: _e.mock.On("FindByIdWithVisits", id)}
}

func (_c *MockPetRepositorier_FindByIdWithVisits_Call) Run(run func(id int)) *MockPetRepositorier_FindByIdWithVisits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPetRepositorier_FindByIdWithVisits_Call) Return(pet *Pet, err error) *MockPetRepositorier_FindByIdWithVisits_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetRepositorier_FindByIdWithVisits_Call) RunAndReturn(run func(id int) (*Pet, error)) *MockPetRepositorier_FindByIdWithVisits_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockPetRepositorier
func (_mock *MockPetRepositorier) FindByName(name string) ([]Pet, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 []Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]Pet, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []Pet); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetRepositorier_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockPetRepositorier_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - name string
func (_e *MockPetRepositorier_Expecter) FindByName(name interface{}) *MockPetRepositorier_FindByName_Call {
	return &MockPetRepositorier_FindByName_Call{Call: _e.mock.On("FindByName", name)}
}

func (_c *MockPetRepositorier_FindByName_Call) Run(run func(name string)) *MockPetRepositorier_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPetRepositorier_FindByName_Call) Return(pets []Pet, err error) *MockPetRepositorier_FindByName_Call {
	_c.Call.Return(pets, err)
	return _c
}

func (_c *MockPetRepositorier_FindByName_Call) RunAndReturn(run func(name string) ([]Pet, error)) *MockPetRepositorier_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockPetRepositorier
func (_mock *MockPetRepositorier) Insert(pet *Pet) (*Pet, error) {
	ret := _mock.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Pet) (*Pet, error)); ok {
		return returnFunc(pet)
	}
	if returnFunc, ok := ret.Get(0).(func(*Pet) *Pet); ok {
		r0 = returnFunc(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Pet) error); ok {
		r1 = returnFunc(pet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetRepositorier_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockPetRepositorier_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - pet *Pet
func (_e *MockPetRepositorier_Expecter) Insert(pet interface{}) *MockPetRepositorier_Insert_Call {
	return &MockPetRepositorier_Insert_Call{Call: _e.mock.On("Insert", pet)}
}

func (_c *MockPetRepositorier_Insert_Call) Run(run func(pet *Pet)) *MockPetRepositorier_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Pet
		if args[0] != nil {
			arg0 = args[0].(*Pet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPetRepositorier_Insert_Call) Return(pet1 *Pet, err error) *MockPetRepositorier_Insert_Call {
	_c.Call.Return(pet1, err)
	return _c
}

func (_c *MockPetRepositorier_Insert_Call) RunAndReturn(run func(pet *Pet) (*Pet, error)) *MockPetRepositorier_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPetRepositorier
func (_mock *MockPetRepositorier) Update(pet *Pet) (*Pet, error) {
	ret := _mock.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Pet) (*Pet, error)); ok {
		return returnFunc(pet)
	}
	if returnFunc, ok := ret.Get(0).(func(*Pet) *Pet); ok {
		r0 = returnFunc(pet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Pet) error); ok {
		r1 = returnFunc(pet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetRepositorier_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPetRepositorier_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - pet *Pet
func (_e *MockPetRepositorier_Expecter) Update(pet interface{}) *MockPetRepositorier_Update_Call {
	return &MockPetRepositorier_Update_Call{Call: _e.mock.On("Update", pet)}
}

func (_c *MockPetRepositorier_Update_Call) Run(run func(pet *Pet)) *MockPetRepositorier_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Pet
		if args[0] != nil {
			arg0 = args[0].(*Pet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPetRepositorier_Update_Call) Return(pet1 *Pet, err error) *MockPetRepositorier_Update_Call {
	_c.Call.Return(pet1, err)
	return _c
}

func (_c *MockPetRepositorier_Update_Call) RunAndReturn(run func(pet *Pet) (*Pet, error)) *MockPetRepositorier_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVetRepositorier creates a new instance of MockVetRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVetRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVetRepositorier {
	mock := &MockVetRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVetRepositorier is an autogenerated mock type for the VetRepositorier type
type MockVetRepositorier struct {
	mock.Mock
}

type MockVetRepositorier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVetRepositorier) EXPECT() *MockVetRepositorier_Expecter {
	return &MockVetRepositorier_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) FindAll() ([]Vet, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []Vet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Vet, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Vet); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Vet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockVetRepositorier_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockVetRepositorier_Expecter) FindAll() *MockVetRepositorier_FindAll_Call {
	return &MockVetRepositorier_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockVetRepositorier_FindAll_Call) Run(run func()) *MockVetRepositorier_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVetRepositorier_FindAll_Call) Return(vets []Vet, err error) *MockVetRepositorier_FindAll_Call {
	_c.Call.Return(vets, err)
	return _c
}

func (_c *MockVetRepositorier_FindAll_Call) RunAndReturn(run func() ([]Vet, error)) *MockVetRepositorier_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPreload provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) FindAllPreload() ([]Vet, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllPreload")
	}

	var r0 []Vet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Vet, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Vet); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Vet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_FindAllPreload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPreload'
type MockVetRepositorier_FindAllPreload_Call struct {
	*mock.Call
}

// FindAllPreload is a helper method to define mock.On call
func (_e *MockVetRepositorier_Expecter) FindAllPreload() *MockVetRepositorier_FindAllPreload_Call {
	return &MockVetRepositorier_FindAllPreload_Call{Call: _e.mock.On("FindAllPreload")}
}

func (_c *MockVetRepositorier_FindAllPreload_Call) Run(run func()) *MockVetRepositorier_FindAllPreload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVetRepositorier_FindAllPreload_Call) Return(vets []Vet, err error) *MockVetRepositorier_FindAllPreload_Call {
	_c.Call.Return(vets, err)
	return _c
}

func (_c *MockVetRepositorier_FindAllPreload_Call) RunAndReturn(run func() ([]Vet, error)) *MockVetRepositorier_FindAllPreload_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllSpecialties provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) FindAllSpecialties() ([]Specialty, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllSpecialties")
	}

	var r0 []Specialty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Specialty, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Specialty); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Specialty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_FindAllSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllSpecialties'
type MockVetRepositorier_FindAllSpecialties_Call struct {
	*mock.Call
}

// FindAllSpecialties is a helper method to define mock.On call
func (_e *MockVetRepositorier_Expecter) FindAllSpecialties() *MockVetRepositorier_FindAllSpecialties_Call {
	return &MockVetRepositorier_FindAllSpecialties_Call{Call: _e.mock.On("FindAllSpecialties")}
}

func (_c *MockVetRepositorier_FindAllSpecialties_Call) Run(run func()) *MockVetRepositorier_FindAllSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVetRepositorier_FindAllSpecialties_Call) Return(specialtys []Specialty, err error) *MockVetRepositorier_FindAllSpecialties_Call {
	_c.Call.Return(specialtys, err)
	return _c
}

func (_c *MockVetRepositorier_FindAllSpecialties_Call) RunAndReturn(run func() ([]Specialty, error)) *MockVetRepositorier_FindAllSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) FindById(id uint) (*Vet, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *Vet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Vet, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Vet); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Vet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockVetRepositorier_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uint
func (_e *MockVetRepositorier_Expecter) FindById(id interface{}) *MockVetRepositorier_FindById_Call {
	return &MockVetRepositorier_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockVetRepositorier_FindById_Call) Run(run func(id uint)) *MockVetRepositorier_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVetRepositorier_FindById_Call) Return(vet *Vet, err error) *MockVetRepositorier_FindById_Call {
	_c.Call.Return(vet, err)
	return _c
}

func (_c *MockVetRepositorier_FindById_Call) RunAndReturn(run func(id uint) (*Vet, error)) *MockVetRepositorier_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdWithSpecialties provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) FindByIdWithSpecialties(id uint) (*Vet, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdWithSpecialties")
	}

	var r0 *Vet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Vet, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Vet); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Vet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_FindByIdWithSpecialties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdWithSpecialties'
type MockVetRepositorier_FindByIdWithSpecialties_Call struct {
	*mock.Call
}

// FindByIdWithSpecialties is a helper method to define mock.On call
//   - id uint
func (_e *MockVetRepositorier_Expecter) FindByIdWithSpecialties(id interface{}) *MockVetRepositorier_FindByIdWithSpecialties_Call {
	return &MockVetRepositorier_FindByIdWithSpecialties_Call{Call: _e.mock.On("FindByIdWithSpecialties", id)}
}

func (_c *MockVetRepositorier_FindByIdWithSpecialties_Call) Run(run func(id uint)) *MockVetRepositorier_FindByIdWithSpecialties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVetRepositorier_FindByIdWithSpecialties_Call) Return(vet *Vet, err error) *MockVetRepositorier_FindByIdWithSpecialties_Call {
	_c.Call.Return(vet, err)
	return _c
}

func (_c *MockVetRepositorier_FindByIdWithSpecialties_Call) RunAndReturn(run func(id uint) (*Vet, error)) *MockVetRepositorier_FindByIdWithSpecialties_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLastName provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) FindByLastName(lastName string) ([]Vet, error) {
	ret := _mock.Called(lastName)

	if len(ret) == 0 {
		panic("no return value specified for FindByLastName")
	}

	var r0 []Vet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]Vet, error)); ok {
		return returnFunc(lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []Vet); ok {
		r0 = returnFunc(lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Vet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_FindByLastName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLastName'
type MockVetRepositorier_FindByLastName_Call struct {
	*mock.Call
}

// FindByLastName is a helper method to define mock.On call
//   - lastName string
func (_e *MockVetRepositorier_Expecter) FindByLastName(lastName interface{}) *MockVetRepositorier_FindByLastName_Call {
	return &MockVetRepositorier_FindByLastName_Call{Call: _e.mock.On("FindByLastName", lastName)}
}

func (_c *MockVetRepositorier_FindByLastName_Call) Run(run func(lastName string)) *MockVetRepositorier_FindByLastName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVetRepositorier_FindByLastName_Call) Return(vets []Vet, err error) *MockVetRepositorier_FindByLastName_Call {
	_c.Call.Return(vets, err)
	return _c
}

func (_c *MockVetRepositorier_FindByLastName_Call) RunAndReturn(run func(lastName string) ([]Vet, error)) *MockVetRepositorier_FindByLastName_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) Insert(vet *Vet) (*Vet, error) {
	ret := _mock.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *Vet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Vet) (*Vet, error)); ok {
		return returnFunc(vet)
	}
	if returnFunc, ok := ret.Get(0).(func(*Vet) *Vet); ok {
		r0 = returnFunc(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Vet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Vet) error); ok {
		r1 = returnFunc(vet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockVetRepositorier_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - vet *Vet
func (_e *MockVetRepositorier_Expecter) Insert(vet interface{}) *MockVetRepositorier_Insert_Call {
	return &MockVetRepositorier_Insert_Call{Call: _e.mock.On("Insert", vet)}
}

func (_c *MockVetRepositorier_Insert_Call) Run(run func(vet *Vet)) *MockVetRepositorier_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Vet
		if args[0] != nil {
			arg0 = args[0].(*Vet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVetRepositorier_Insert_Call) Return(vet1 *Vet, err error) *MockVetRepositorier_Insert_Call {
	_c.Call.Return(vet1, err)
	return _c
}

func (_c *MockVetRepositorier_Insert_Call) RunAndReturn(run func(vet *Vet) (*Vet, error)) *MockVetRepositorier_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVetRepositorier
func (_mock *MockVetRepositorier) Update(vet *Vet) (*Vet, error) {
	ret := _mock.Called(vet)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Vet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Vet) (*Vet, error)); ok {
		return returnFunc(vet)
	}
	if returnFunc, ok := ret.Get(0).(func(*Vet) *Vet); ok {
		r0 = returnFunc(vet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Vet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Vet) error); ok {
		r1 = returnFunc(vet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVetRepositorier_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVetRepositorier_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - vet *Vet
func (_e *MockVetRepositorier_Expecter) Update(vet interface{}) *MockVetRepositorier_Update_Call {
	return &MockVetRepositorier_Update_Call{Call: _e.mock.On("Update", vet)}
}

func (_c *MockVetRepositorier_Update_Call) Run(run func(vet *Vet)) *MockVetRepositorier_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Vet
		if args[0] != nil {
			arg0 = args[0].(*Vet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVetRepositorier_Update_Call) Return(vet1 *Vet, err error) *MockVetRepositorier_Update_Call {
	_c.Call.Return(vet1, err)
	return _c
}

func (_c *MockVetRepositorier_Update_Call) RunAndReturn(run func(vet *Vet) (*Vet, error)) *MockVetRepositorier_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVisitRepositorier creates a new instance of MockVisitRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitRepositorier {
	mock := &MockVisitRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVisitRepositorier is an autogenerated mock type for the VisitRepositorier type
type MockVisitRepositorier struct {
	mock.Mock
}

type MockVisitRepositorier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitRepositorier) EXPECT() *MockVisitRepositorier_Expecter {
	return &MockVisitRepositorier_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockVisitRepositorier
func (_mock *MockVisitRepositorier) FindAll() ([]Visit, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Visit, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Visit); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepositorier_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockVisitRepositorier_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockVisitRepositorier_Expecter) FindAll() *MockVisitRepositorier_FindAll_Call {
	return &MockVisitRepositorier_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockVisitRepositorier_FindAll_Call) Run(run func()) *MockVisitRepositorier_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVisitRepositorier_FindAll_Call) Return(visits []Visit, err error) *MockVisitRepositorier_FindAll_Call {
	_c.Call.Return(visits, err)
	return _c
}

func (_c *MockVisitRepositorier_FindAll_Call) RunAndReturn(run func() ([]Visit, error)) *MockVisitRepositorier_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockVisitRepositorier
func (_mock *MockVisitRepositorier) FindById(id uint) (*Visit, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Visit, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Visit); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepositorier_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockVisitRepositorier_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uint
func (_e *MockVisitRepositorier_Expecter) FindById(id interface{}) *MockVisitRepositorier_FindById_Call {
	return &MockVisitRepositorier_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockVisitRepositorier_FindById_Call) Run(run func(id uint)) *MockVisitRepositorier_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVisitRepositorier_FindById_Call) Return(visit *Visit, err error) *MockVisitRepositorier_FindById_Call {
	_c.Call.Return(visit, err)
	return _c
}

func (_c *MockVisitRepositorier_FindById_Call) RunAndReturn(run func(id uint) (*Visit, error)) *MockVisitRepositorier_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockVisitRepositorier
func (_mock *MockVisitRepositorier) Insert(visit *Visit) (*Visit, error) {
	ret := _mock.Called(visit)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Visit) (*Visit, error)); ok {
		return returnFunc(visit)
	}
	if returnFunc, ok := ret.Get(0).(func(*Visit) *Visit); ok {
		r0 = returnFunc(visit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Visit) error); ok {
		r1 = returnFunc(visit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepositorier_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockVisitRepositorier_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - visit *Visit
func (_e *MockVisitRepositorier_Expecter) Insert(visit interface{}) *MockVisitRepositorier_Insert_Call {
	return &MockVisitRepositorier_Insert_Call{Call: _e.mock.On("Insert", visit)}
}

func (_c *MockVisitRepositorier_Insert_Call) Run(run func(visit *Visit)) *MockVisitRepositorier_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Visit
		if args[0] != nil {
			arg0 = args[0].(*Visit)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVisitRepositorier_Insert_Call) Return(visit1 *Visit, err error) *MockVisitRepositorier_Insert_Call {
	_c.Call.Return(visit1, err)
	return _c
}

func (_c *MockVisitRepositorier_Insert_Call) RunAndReturn(run func(visit *Visit) (*Visit, error)) *MockVisitRepositorier_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVisitRepositorier
func (_mock *MockVisitRepositorier) Update(visit *Visit) (*Visit, error) {
	ret := _mock.Called(visit)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Visit) (*Visit, error)); ok {
		return returnFunc(visit)
	}
	if returnFunc, ok := ret.Get(0).(func(*Visit) *Visit); ok {
		r0 = returnFunc(visit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Visit) error); ok {
		r1 = returnFunc(visit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepositorier_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVisitRepositorier_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - visit *Visit
func (_e *MockVisitRepositorier_Expecter) Update(visit interface{}) *MockVisitRepositorier_Update_Call {
	return &MockVisitRepositorier_Update_Call{Call: _e.mock.On("Update", visit)}
}

func (_c *MockVisitRepositorier_Update_Call) Run(run func(visit *Visit)) *MockVisitRepositorier_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Visit
		if args[0] != nil {
			arg0 = args[0].(*Visit)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVisitRepositorier_Update_Call) Return(visit1 *Visit, err error) *MockVisitRepositorier_Update_Call {
	_c.Call.Return(visit1, err)
	return _c
}

func (_c *MockVisitRepositorier_Update_Call) RunAndReturn(run func(visit *Visit) (*Visit, error)) *MockVisitRepositorier_Update_Call {
	_c.Call.Return(run)
	return _c
}
