// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package owner

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServicer creates a new instance of MockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicer {
	mock := &MockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

type MockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicer) EXPECT() *MockServicer_Expecter {
	return &MockServicer_Expecter{mock: &_m.Mock}
}

// create provides a mock function for the type MockServicer
func (_mock *MockServicer) create(ownerRequest *AddRequest) (*Response, error) {
	ret := _mock.Called(ownerRequest)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*AddRequest) (*Response, error)); ok {
		return returnFunc(ownerRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*AddRequest) *Response); ok {
		r0 = returnFunc(ownerRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*AddRequest) error); ok {
		r1 = returnFunc(ownerRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type MockServicer_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - ownerRequest *AddRequest
func (_e *MockServicer_Expecter) create(ownerRequest interface{}) *MockServicer_create_Call {
	return &MockServicer_create_Call{Call: _e.mock.On("create", ownerRequest)}
}

func (_c *MockServicer_create_Call) Run(run func(ownerRequest *AddRequest)) *MockServicer_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *AddRequest
		if args[0] != nil {
			arg0 = args[0].(*AddRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_create_Call) Return(response *Response, err error) *MockServicer_create_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServicer_create_Call) RunAndReturn(run func(ownerRequest *AddRequest) (*Response, error)) *MockServicer_create_Call {
	_c.Call.Return(run)
	return _c
}

// getAllOwners provides a mock function for the type MockServicer
func (_mock *MockServicer) getAllOwners() (*Responses, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAllOwners")
	}

	var r0 *Responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*Responses, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *Responses); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getAllOwners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAllOwners'
type MockServicer_getAllOwners_Call struct {
	*mock.Call
}

// getAllOwners is a helper method to define mock.On call
func (_e *MockServicer_Expecter) getAllOwners() *MockServicer_getAllOwners_Call {
	return &MockServicer_getAllOwners_Call{Call: _e.mock.On("getAllOwners")}
}

func (_c *MockServicer_getAllOwners_Call) Run(run func()) *MockServicer_getAllOwners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicer_getAllOwners_Call) Return(responses *Responses, err error) *MockServicer_getAllOwners_Call {
	_c.Call.Return(responses, err)
	return _c
}

func (_c *MockServicer_getAllOwners_Call) RunAndReturn(run func() (*Responses, error)) *MockServicer_getAllOwners_Call {
	_c.Call.Return(run)
	return _c
}

// getOwnerById provides a mock function for the type MockServicer
func (_mock *MockServicer) getOwnerById(id uint) (*Response, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getOwnerById")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Response, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Response); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getOwnerById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getOwnerById'
type MockServicer_getOwnerById_Call struct {
	*mock.Call
}

// getOwnerById is a helper method to define mock.On call
//   - id uint
func (_e *MockServicer_Expecter) getOwnerById(id interface{}) *MockServicer_getOwnerById_Call {
	return &MockServicer_getOwnerById_Call{Call: _e.mock.On("getOwnerById", id)}
}

func (_c *MockServicer_getOwnerById_Call) Run(run func(id uint)) *MockServicer_getOwnerById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getOwnerById_Call) Return(response *Response, err error) *MockServicer_getOwnerById_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServicer_getOwnerById_Call) RunAndReturn(run func(id uint) (*Response, error)) *MockServicer_getOwnerById_Call {
	_c.Call.Return(run)
	return _c
}

// getOwnerByIdWithPets provides a mock function for the type MockServicer
func (_mock *MockServicer) getOwnerByIdWithPets(id uint) (*Response, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getOwnerByIdWithPets")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Response, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Response); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getOwnerByIdWithPets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getOwnerByIdWithPets'
type MockServicer_getOwnerByIdWithPets_Call struct {
	*mock.Call
}

// getOwnerByIdWithPets is a helper method to define mock.On call
//   - id uint
func (_e *MockServicer_Expecter) getOwnerByIdWithPets(id interface{}) *MockServicer_getOwnerByIdWithPets_Call {
	return &MockServicer_getOwnerByIdWithPets_Call{Call: _e.mock.On("getOwnerByIdWithPets", id)}
}

func (_c *MockServicer_getOwnerByIdWithPets_Call) Run(run func(id uint)) *MockServicer_getOwnerByIdWithPets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getOwnerByIdWithPets_Call) Return(response *Response, err error) *MockServicer_getOwnerByIdWithPets_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServicer_getOwnerByIdWithPets_Call) RunAndReturn(run func(id uint) (*Response, error)) *MockServicer_getOwnerByIdWithPets_Call {
	_c.Call.Return(run)
	return _c
}

// getOwnerByLastName provides a mock function for the type MockServicer
func (_mock *MockServicer) getOwnerByLastName(lastName string) (*Responses, error) {
	ret := _mock.Called(lastName)

	if len(ret) == 0 {
		panic("no return value specified for getOwnerByLastName")
	}

	var r0 *Responses
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Responses, error)); ok {
		return returnFunc(lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Responses); ok {
		r0 = returnFunc(lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Responses)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_getOwnerByLastName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getOwnerByLastName'
type MockServicer_getOwnerByLastName_Call struct {
	*mock.Call
}

// getOwnerByLastName is a helper method to define mock.On call
//   - lastName string
func (_e *MockServicer_Expecter) getOwnerByLastName(lastName interface{}) *MockServicer_getOwnerByLastName_Call {
	return &MockServicer_getOwnerByLastName_Call{Call: _e.mock.On("getOwnerByLastName", lastName)}
}

func (_c *MockServicer_getOwnerByLastName_Call) Run(run func(lastName string)) *MockServicer_getOwnerByLastName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicer_getOwnerByLastName_Call) Return(responses *Responses, err error) *MockServicer_getOwnerByLastName_Call {
	_c.Call.Return(responses, err)
	return _c
}

func (_c *MockServicer_getOwnerByLastName_Call) RunAndReturn(run func(lastName string) (*Responses, error)) *MockServicer_getOwnerByLastName_Call {
	_c.Call.Return(run)
	return _c
}

// update provides a mock function for the type MockServicer
func (_mock *MockServicer) update(id uint, updateOwner *UpdateRequest) (*UpdateResponse, error) {
	ret := _mock.Called(id, updateOwner)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 *UpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, *UpdateRequest) (*UpdateResponse, error)); ok {
		return returnFunc(id, updateOwner)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, *UpdateRequest) *UpdateResponse); ok {
		r0 = returnFunc(id, updateOwner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UpdateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, *UpdateRequest) error); ok {
		r1 = returnFunc(id, updateOwner)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServicer_update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'update'
type MockServicer_update_Call struct {
	*mock.Call
}

// update is a helper method to define mock.On call
//   - id uint
//   - updateOwner *UpdateRequest
func (_e *MockServicer_Expecter) update(id interface{}, updateOwner interface{}) *MockServicer_update_Call {
	return &MockServicer_update_Call{Call: _e.mock.On("update", id, updateOwner)}
}

func (_c *MockServicer_update_Call) Run(run func(id uint, updateOwner *UpdateRequest)) *MockServicer_update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *UpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*UpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicer_update_Call) Return(updateResponse *UpdateResponse, err error) *MockServicer_update_Call {
	_c.Call.Return(updateResponse, err)
	return _c
}

func (_c *MockServicer_update_Call) RunAndReturn(run func(id uint, updateOwner *UpdateRequest) (*UpdateResponse, error)) *MockServicer_update_Call {
	_c.Call.Return(run)
	return _c
}
